### ISSUE TITLE
how to sort the query result

### ISSUE THREAD

**Issue by swifth** [Oyvindkg/swiftydb#17]
how to sort the query result? Only filter found. we want something like sortBy id desc, etc.

**Comment by Oyvindkg** [comment]
At the moment, `ORDER BY` is not supported. Unfortunately I don't think I have got the time to anything about it before May. You are welcome to implement something and send a pull request, if you have the time :)

Until then, maybe you could use Swift's sort methods instead? They might be a bit slower, depending on your data/queries, but unless you have huge datasets, they will probably do the trick!

**Comment by swifth** [comment]
I had fork a branch : https://github.com/swifth/SwifthDB . and add support for order by and carthage support. and removed the multiple SQLiteDatatype definition. and fixed others bugs.  But I have no idea how to merge into master.
