### ISSUE TITLE
is swiftydb support "select * from table where a like '%1%' or b like '%1%' or c like '%1%' " ?

### ISSUE THREAD

**Issue by kingtami** [Oyvindkg/swiftydb#19]
title is the trouble,thanks.

**Comment by Oyvindkg** [comment]
The 'OR' operator isn't available at this time, but it will probably be included in a future update.
My best advise would be to issue multiple queries, and merge the results. I know that this isn't an optimal solution

**Comment by Oyvindkg** [comment]
This is supported in the upcoming v2.0

**Comment by Oyvindkg** [comment]
Feel free to play around with the ´dev´ branch. It is a major improvement to the original SwiftyDB in both implementation and usability, and it sports a powerful query language!
