### ISSUE TITLE
Missing Column

### ISSUE THREAD

**Issue by toptierlabs** [Oyvindkg/swiftydb#27]
I am using SwiftyDB in conjunction with TinySQLite.
On some cases, when I install a new version that adds new columns to my SQLite scheme, it isn't get updated for some reason.

On a new install, we clean up the database. We completely delete all the records, but not the tables.

The app crashes because a couple of columns are missing. I have no idea why.

**Comment by Oyvindkg** [comment]
Unfortunately, the current version does not support migration. 

This is fixed in version 2.0, which is meant to be released soon (https://github.com/Oyvindkg/swiftydb/blob/swiftydb-2.0-dev/README.md)
