### ISSUE TITLE
TinySQLite in SwiftDB does not support Swift 3

### ISSUE THREAD

**Issue by mdfalcon104** [Oyvindkg/swiftydb#30]
Hi your library is using the TinySQLite library but I see it has not upgraded to Swift 3? Is the current version 2.0 support running without any problem?

**Comment by Oyvindkg** [comment]
Neither SwiftyDB or TinySQLite currently supports Swift 3.0

**Comment by steelzeh** [comment]
Any news about this?

**Comment by Oyvindkg** [comment]
Sorry for the long wait. The past few months have been crazy juggeling work at a startup (https://flowmotion.one) and finishing my masters degree. I really hope to be able to complete v2.0 for Swift 3 as soon as possible, but I at this point I cannot give you a date.

**Comment by mikestalker** [comment]
Any news?

**Comment by Oyvindkg** [comment]
TinySQLite now supports Swift 3.0.

I have revised the 2.0 implementation and interface. If you are interested, have a look at [the README](https://github.com/Oyvindkg/swiftydb/blob/dev/README.md) and tell me what you think. As soon as the test coverage is improved, and the interfaces are done, I'll push a new release. 

Feel free to play around with the ´dev´ branch. It is a major improvement to the original SwiftyDB in both implementation and usability.
