### ISSUE TITLE
Cannot invoke 'asyncDataForType' with an argument list of type '(SiteRecord.Type, (_) -> Void)'

### ISSUE THREAD

**Issue by jeffery812** [Oyvindkg/swiftydb#5]
What's wrong with my code, did I do something wrong?

> let database = SwiftyDB(databaseName: "gogogo")
> database.asyncDataForType(SiteRecord.self) { (result) -> Void in
> }            

/Users/zhihuitang/repo/ios/Letsgo/Letsgo/JSBridgeHandler.swift:32:18: Cannot invoke 'asyncDataForType' with an argument list of type '(SiteRecord.Type, (_) -> Void)'

**Comment by Oyvindkg** [comment]
Your code looks good to me. Does 'SiteRecord' implement the 'Storable' protocol?

**Comment by jeffery812** [comment]
sorry, you are right. my Storable has some problem. thanks
