### ISSUE TITLE
when Filter.contains("property",array:[String]), fatal error: can't unsafeBitCast between types of different sizes

### ISSUE THREAD

**Issue by hosven** [Oyvindkg/swiftydb#8]
when Filter.contains("property",array:[String]), 
fatal error: can't unsafeBitCast between types of different sizes
help

**Comment by Oyvindkg** [comment]
Sorry for the slow response. Have you figured it out? If not, could you provide a more detailed stack trace? It would make it easier to understand the problem you are experiencing.

**Comment by hosven** [comment]
when Filter.contains("propertyName",array:[String])
when the array is a new init [String] array, it causes the fatal error.
when i create the objects : Storable, then get the string property of them as [String] , it's ok.

**Comment by Oyvindkg** [comment]
If I understand you correctly, you are providing an empty array as parameter to the filter, and this causes a fatal error? 

If that is the case, I will fix it as soon as possible.

**Comment by Oyvindkg** [comment]
Maybe you could provide some illustrating code so I can see what is going on? :)
